### ISSUE TITLE
implement `gofish bump`

### ISSUE THREAD

**Issue by eloo** [fishworks/gofish#112]
Hi,
i'm testing/using gofish since a few weeks and really like the idea but updating food is in my opinion a bit to unhandy.. at the moment i need to update the version and all checksums, which can be many..
also many project are already providing the checksum for each release in a separate file.. 
so it be really great if the could use these files for verifying downloads.. 
if this would be possible a update of my food would be only to increment the version itself.. so updating food would be a small step and can be done quickly..
so what do you think? could this be an option?

thanks
eloo

**Comment by bacongobbler** [comment]
The one problem I foresee is that of ensuring data integrity. I'm not sure if I would trust fetching a file from the internet over HTTP(s) to verify that the checksums are correct for the given package, as that file could have been tampered with via a man-in-the-middle attack. The nice thing about having the checksum embedded within the manifest is that it ensures that if I trust a git repository with a given set of manifests, the checksum cannot be man-in-the-middle'd, so even if the package is tampered through a MitM attack, we can loosely verify its data integrity is intact and inform the user that the package failed the checksum check with a probable cause.

Now, that all being said...

One convention Homebrew maintainers have done in the past is to implement a `sha256_checksum` function, which when called will return a checksum as a string.

For example, one example would be

```
def self.sha256_checksum
  @sha256_checksum ||= begin
    `curl --silent https://example.com/mypackage-v0.1.0.tar.gz.sha256`.split.first
  end
end

sha256 sha256_checksum
```

For GoFish, this could be handled by allowing external packages into the Lua VM (like [lua-http](https://github.com/daurnimator/lua-http)), which then package authors could use to express how to fetch the shasum within the script itself.

In Lua, this could be resolved like this:

```
local name = "gofish"
local version = "0.10.0"

local http_request = require "http.request"
local headers, stream = assert(http_request.new_from_uri("https://gofi.sh/releases/" .. name .. "-v" .. version .. "-darwin-amd64.tar.gz.sha256"):go())
local darwin_sha256 = assert(stream:get_body_as_string())
if headers:get ":status" ~= "200" then
    error(darwin_sha256)
end
```

Then later down in the food:

```
sha256 = darwin_sha256,
```

Would that handle your use case?

**Comment by bacongobbler** [comment]
> so what do you think? could this be an option?

Allow me to flip this question back around: this is a project I maintain on my free time for personal use. I'm not particularly interested in this feature so I probably won't get around to implementing this myself, but I'd be more than happy to point others in the right direction. If you're interested in this feature, would you be willing to take the time to contribute?

**Comment by eloo** [comment]
@bacongobbler 
okay yeah i totally understand your point.. 
but having such a express in every food is maybe also not the really nice..
another idea could be to have a gofish function to update the sha256 value of my food..
for example..
- i update the version of the file to download.. 
- now my git food repo is dirty
- i run some like gofish update-sha my-food
- gofish will download all configured files.. calculates the sha256 and may check if there is a .sha256 file available and validates the checksums
- gofish will overwrite the sha256 values in my-food.lua with the downloaded and validated values
- update complete

This will decrease the chance of MITM to one single execution because afterwards the "hardcoded" checksum will be used.

maybe this would be a more generic solution because the command could be used for already existing foods also..

what do you think?

PS: and yes if i find some time to get familiar with the gofish code i would try to implement something like this ;)

**Comment by bacongobbler** [comment]
I  think the idea of updating the shasums through some form of command like `gofish bump gofish 1.4.0` would be a great feature, or possibly a plugin. In fact it’d help me a lot with keeping the existing packages on fish-food up to date.

**Comment by eloo** [comment]
@bacongobbler is there any progress on this topic?

**Comment by bacongobbler** [comment]
[Nope](https://github.com/fishworks/gofish/issues/112#issuecomment-418873800). Feel free to take this one on.

**Comment by karuppiah7890** [comment]
I tried something like this, but it seems a bit hacky as I couldn't manipulate the lua file. Here's the solution - https://github.com/karuppiah7890/uff

**Comment by karuppiah7890** [comment]
I'm guessing writing something in lua might give an elegant solution. Not so sure though

**Comment by eloo** [comment]
@karuppiah7890 
i've tested your tool and it looks good. but it is a little bit slow.
it took over 10 minutes to update gitea with 4 packages. 
I've checked your code and i guess the part with the download is a bit slow. further for some packages it should not be necessary to download it and calculate the sha256 because the sha256 is already online.
so simply download the sha file and use the checksum in it should be also fine.

what do you think?

**Comment by karuppiah7890** [comment]
I agree. It's just that finding the sha256 file is not always straight
forward. Some put it as download-file-na.sha256 or so. I have seen some
people put all shasums for archives of all platforms in one file. We can do
something intelligent, and if it's not possible, use download and find
shasum

**Comment by eloo** [comment]
@karuppiah7890 
yeah that sounds like a proper solution.
i've the checksum can be found easily use it otherwise use download and manual calculation as a fallback 👍

**Comment by karuppiah7890** [comment]
Cool then, you want to go ahead and build it?

**Comment by eloo** [comment]
@karuppiah7890 
yes i can have a look and implement it. but it take some time because i'm busy the next two weeks

**Comment by bacongobbler** [comment]
closing as resolved via third-party tools like `uff`.
