### ISSUE TITLE
Configure gofish to work behind proxy

### ISSUE THREAD

**Issue by JPShee** [fishworks/gofish#133]
I am trying to use gofish but during init I get the error 
``==> Installing default fish food...
Error: Unable to get repository: Cloning into 'C:\ProgramData\Fish\Rigs\github.com\fishworks\fish-food'...
fatal: unable to access 'https://github.com/fishworks/fish-food/': Failed to connect to github.com port 443: Timed out
: exit status 128``

I am fairly confident this is as a result of the corporate proxy at work, is there a way to supply that proxy info to gofish?

**Comment by bacongobbler** [comment]
Not that I'm aware of at this time. Feel free to work on a fix or some documentation on how users can overcome this.

**Comment by vharsh** [comment]
@JPShee Does setting `HTTP_PROXY` and `HTTPS_PROXY` environment variables before running the `gofish` commands work in Windows?
Most *nix tools and others respect these environment variables.

**Comment by bacongobbler** [comment]
closing as answered/inactive. Please let us know how you get along with @vharsh's suggestion. Happy to accept PRs that document this behaviour. Thanks!
