### ISSUE TITLE
How to handle major version changes / breaking changes ?

### ISSUE THREAD

**Issue by karuppiah7890** [fishworks/gofish#141]
Helm v3 has been released. Should we update food to that version?

Taking terraform example, we have updated it always, irrespective of breaking changes

**Comment by karuppiah7890** [comment]
Is it okay to have another food for helm-2? And keep updating it separately? But yeah, there will be a confusion as to which version people are using, if they have installed both the food, unless they use helm version and check. Since both give same binary helm

**Comment by bacongobbler** [comment]
there is precedence for this now via https://github.com/fishworks/fish-food/pull/485.

tl;dr:

`helm`: tracks the absolute latest version. It isn't constrained to a particular major version
`helm@2`: tracks the latest version of Helm 2.

**Comment by karuppiah7890** [comment]
Awesome! 😄
