### ISSUE TITLE
support Chromebook

### ISSUE THREAD

**Issue by gedw99** [fishworks/gofish#145]
Since Chromebook is just debian, it might be possibel to support Chrome books.

i can run golang, flutter, vscode.
pretty sure i can run k8 also but just working through it.

For example when you curl a .deb into the Linux downloads and double click it installs it.
Its quite dev friendly now

**Comment by bacongobbler** [comment]
if you find issues running gofish on chromebook, please feel free to file tickets. I don't think there's anything we need to do specifically to support chromebook so it should be supported as-is.
