### ISSUE TITLE
Support for .tar.xz archives?

### ISSUE THREAD

**Issue by SeekingMeaning** [fishworks/gofish#146]
Would .tar.xz support be possible? Here's a sample file: https://downloads.haskell.org/~cabal/cabal-install-latest/cabal-install-3.0.0.0-x86_64-apple-darwin17.7.0.tar.xz

**Comment by bacongobbler** [comment]
Have you started looking into this? I don’t have the time to work on this right now but I’d accept a patch.

**Comment by SeekingMeaning** [comment]
I tried, but unfortunately I’m not too experienced with Go. Would you be able to give any pointers?

**Comment by bacongobbler** [comment]
https://github.com/fishworks/gofish/blob/master/food.go#L185-L190

**Comment by SeekingMeaning** [comment]
See #147, although I'll admit I'm not really sure what I'm doing

**Comment by bacongobbler** [comment]
Sorry. I have a lot on my plate right now so I haven't had time to look further into this. I'm going to keep this open and have a look at re-implementing #147 when I have the time. This would still be a nice feature to have.
