### ISSUE TITLE
Command aliases?

### ISSUE THREAD

**Issue by SeekingMeaning** [fishworks/gofish#157]
For example, `gofish remove` and `gofish rm` would be the same as `gofish uninstall`

**Comment by bacongobbler** [comment]
Should be very easy to implement. Cobra has built-in support for command aliases.

https://godoc.org/github.com/spf13/cobra#Command

**Comment by bacongobbler** [comment]
https://github.com/fishworks/gofish/blob/7ffd9b5ecf427284c425eb86830a53e427eda5f9/cmd/gofish/uninstall.go#L13-L16
