### ISSUE TITLE
gofish pin <food> Hint failed

### ISSUE THREAD

**Issue by snuglove** [fishworks/gofish#161]
root@gofish fish-food/Food (master) » gofish list 
NAME
go  
helm

root@gofish fish-food/Food (master) » gofish pin go
Error: `gofish pin` is not implemented

root@gofish fish-food/Food (master) » gofish pin helm                                                                                          1 ↵
Error: `gofish pin` is not implemented

**Comment by bacongobbler** [comment]
I’m confused. This command does not exist yet. See #14.

What was the expected result?

**Comment by snuglove** [comment]
According to Gofish, the pin is used to lock in fish food for the purpose of blocking updates;
Read # 14, There is no gofish hook parameter in the help,It's unusable

**Comment by bacongobbler** [comment]
`gofish pin` has not been implemented. It does not exist. Please follow #14 for updates.
