### ISSUE TITLE
Linux installation failed

### ISSUE THREAD

**Issue by yuvrajsab** [fishworks/gofish#171]
I was following install instructions on gofi.sh and getting this error.

```bash
curl -fsSL https://raw.githubusercontent.com/fishworks/gofish/master/scripts/install.sh | bash
url: (22) The requested URL returned error: 404 Not Found
```

**Comment by bacongobbler** [comment]
Hi @yuvrajsab. Thanks for catching that. I'll go update the instructions on the site.

In the meantime, the correct installation instructions are the following (switching `master` to `main`):

```
$ curl -fsSL https://raw.githubusercontent.com/fishworks/gofish/main/scripts/install.sh | bash
```

**Comment by bacongobbler** [comment]
Fixed in https://github.com/fishworks/gofi.sh/commit/c5b6b8dac65fa4171b10df4277da6864db18e730, which should come online in a few minutes. Thanks for the heads up.
