### ISSUE TITLE
Can't install 0.13.0 on Mac

### ISSUE THREAD

**Issue by alecthomas** [fishworks/gofish#172]
https://gofi.sh/releases/gofish-v0.13.0-macos-amd64.tar.gz results in an error page.

**Comment by alecthomas** [comment]
> Well, a fine little mess. Easy in, easy out. Another triumph.

**Comment by bacongobbler** [comment]
The correct URL is https://gofi.sh/releases/gofish-v0.13.0-darwin-amd64.tar.gz. Is there a place I should update the download URL?

**Comment by alecthomas** [comment]
I just followed the install instructions.

**Comment by alecthomas** [comment]
Sorry, was on my phone so I was a bit terse. Following the installation instructions:

```
➜ ~ curl -fsSL https://raw.githubusercontent.com/fishworks/gofish/main/scripts/install.sh | bash

Downloading https://gofi.sh/releases/gofish-v0.13.0-macos-amd64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   837    0   837    0     0   1173      0 --:--:-- --:--:-- --:--:--  1172
tar: Error opening archive: Unrecognized archive format
!!!	Failed to install gofish
!!!	For support, go to https://github.com/fishworks/gofish.
```

**Comment by bacongobbler** [comment]
fixed in https://github.com/fishworks/gofish/commit/309ee2606318c9aab91510e8b7313b5e5712522f.
