### ISSUE TITLE
gofish update and gofish upgrade fails to update repository

### ISSUE THREAD

**Issue by bjornmagnusson** [fishworks/gofish#173]
When running **gofish update** or **gofish upgrade** the CLI fails to update repository and outputs **Error: Unable to update repository: exit status 1**

Running gofish in WSL

`gofish version
v0.10.0`

`cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic`

**Comment by bacongobbler** [comment]
If you switch directories into $GOFISH_DEFAULT_RIG (use `gofish tank` to find the value), does `git status` show anything odd? Also try `git pull` from there.

I recently switched the main branch from `master` to `main` for fish-food, which may be causing the failure to update. You may be able to fix this by running `git checkout -b main && git pull`. Once you have `git pull` working again, things should work as usual.

Worst case scenario: run `cd $GOFISH_DEFAULT_RIG; cd ..; rm -rf $GOFISH_DEFAULT_RIG; gofish init` to re-initialize the default rig. This will not cause any update issues with your existing installation.

**Comment by bacongobbler** [comment]
Bring 3 versions behind latest might also be an issue here... As always, make sure this hasn't already been fixed with a newer version.

**Comment by bjornmagnusson** [comment]
Resolved it by installing the newest version. However had to re-install all fish-foods previously installed to appear in gofish list. Thanks for help
