### ISSUE TITLE
Update Old/Current Release Documentation to reflect new branch name.

### ISSUE THREAD

**Issue by jakesyl** [fishworks/gofish#175]
The latest/previous release commands currently 40 because they point to the `master` branch rather than the `main` branch:

![image](https://user-images.githubusercontent.com/6392429/91106340-68df9500-e640-11ea-9467-fba735052822.png)

![image](https://user-images.githubusercontent.com/6392429/91106401-8a408100-e640-11ea-9b79-47bb9d76b805.png)

It'd be nice to have some kind of redirect in place to keep ci builds working.

Thanks!

**Comment by bacongobbler** [comment]
I updated the URL in the release page to reflect the new location. Thanks.
