### ISSUE TITLE
Feature request: Creating symlinks under $GOFISH_BINPATH

### ISSUE THREAD

**Issue by mumoshu** [fishworks/gofish#176]
Hi! Thanks for starting and sharing this awesome project ☺️ 

I'm using `gofish` to install "project dependencies", not system-wide dependencies, i.e. to manage symlinks across many directories other than `/usr/local/bin`.

After reading gofish code, I realized that there is an envvar named `$GOFISH_BINPATH`, that is read by gofish, expected setting it to somewhere other than `/usr/loca/bin` would do my job, but it didn't. 

Let's say I want to install `go` under `$(pwd)/.tools/bin`, I'd run:

```
export GOFISH_BINPATH=$(pwd)/.tools/bin

gofish init
gofish install go
```

so that I can use the project-specific `go` by setting:

```
export PATH=$GOFISH_BINPATH:${PATH}
```

But this doesn't work as I wanted. `init` created `$(pwd)/.tools/bin`, but `install` installed the symlink under `/usr/local/bin` on my macOS and Linux machines, regardless of what I set to `GOFISH_BINPATH`.

Can we make `GOFISH_BINPATH` to change where the `install` command installs symlinks?
Or would there be any other (possible) workaround or feature to address my use-case?

Thanks!

Related https://github.com/fishworks/gofish/pull/174

**Comment by mumoshu** [comment]
@bacongobbler I'm replying your comment in #174 -

> Keep in mind that it is entirely possible a user would want to install packages into locations other than /usr/local/bin. For example, manpages may want to be installed under /usr/local/man, and libraries under /usr/local/include

I'm assuming that you're describing about the cases that you declare resources for respective paths in your food written in lua, right? I believe my goal is a bit different then.

For example, given [the `go` food that has `installpath = "bin/go` for the go binary](https://github.com/fishworks/fish-food/blob/main/Food/go.lua#L19), I'd like to install it under `$(pwd)/.tools/bin/go` without changing the Food itself.

**Comment by bacongobbler** [comment]
So if I'm understanding correctly, is this similar to the request being asked in #150? I've been strongly considering re-architecting gofish as a user-level package manager. That's what most users have been asking for in any case.

If so, then perhaps we should consider breaking backwards compatibility, allow GOFISH_BIN to be modified, and then go one step further and consider changing the default for `HomePrefix` to be something within the user's homepath by default.

What do you think about that approach?

**Comment by mumoshu** [comment]
@bacongobbler Thanks! Yes, although I didn't realize that before, this issue seems like a subset of #150.

Your approach sounds great 👍 

Also, I'm wondering if we'd better remove `GOFISH_BINPATH` as unnecessary after the change. WDYT?

**Comment by bacongobbler** [comment]
Yeah, I think GOFISH_BIN would be unnecessary after that change, so I’d agree to remove it. :)

**Comment by azilber** [comment]
> Yeah, I think GOFISH_BIN would be unnecessary after that change, so I’d agree to remove it. :)

Any ETA on this?  It's almost a year later...  😅

**Comment by bacongobbler** [comment]
This is a freely available open source project I use and maintain after regular work hours. I’m not paid by anyone to work on this.

If you’d like to see something implemented, please feel free to hack away on something.

**Comment by bacongobbler** [comment]
closing in favour of #150.
