### ISSUE TITLE
feature: ability to swap out the default rig

### ISSUE THREAD

**Issue by shakefu** [fishworks/gofish#187]
It looks like no matter what it's searching the default "Rig" even if it has been removed. Also it looks like support for Private or SSH based repos doesn't work? 
![image](https://user-images.githubusercontent.com/1046227/133152554-ac9de456-0d8b-4df9-bd11-6dce219b9f30.png)

If there's any way to configure `gofish` to use a private Fish Food repository instead of the default, this would be an amazing tool.

**Comment by bacongobbler** [comment]
Hmm... You should be able specify the rig name as part of the package. This was put in place to ensure that the right package is chosen when two rigs with conflicting packages are added.

In other words: `gofish install github.com/shakefu/fish-food/go`.

I'd be happy to accept a PR that can either

1. set a "default" rig, such that `gofish install go` would lookup under your fork
2. use the only rig available as the default if no other rigs are installed

Either option should solve your use case.

**Comment by bacongobbler** [comment]
Updated the title to reflect the ask.

**Comment by shakefu** [comment]
Even with the default rig enabled `gofish search go` doesn't show the food in the added rig. Is this the expected behavior without the prefix?

**Comment by shakefu** [comment]
Looks like the default rig is _required_ to be present otherwise it breaks:
![image](https://user-images.githubusercontent.com/1046227/133154536-5e59e5f2-503a-4742-9917-f7983c4e8fdc.png)

Searching does return the custom recipe if a partial prefix is supplied:
![image](https://user-images.githubusercontent.com/1046227/133154653-bcad155b-3d3f-4d21-80fd-9843ca7eaa33.png)

**Comment by bacongobbler** [comment]
Worked for me just fine. Here's how I tested:

```
><> gofish rig remove github.com/fishworks/fish-food
🐠  rigs uninstalled in 1.764489ms
><> gofish rig add https://github.com/bacongobbler/fish-food
🐠  rig constructed in 1.097866964s
><> gofish rig list
NAME                             
github.com/bacongobbler/fish-food
><> gofish install wasmtime
==> Installing github.com/bacongobbler/fish-food/wasmtime...
🐠  wasmtime 0.29.0: installed in 1.130998062s
><> gofish search go | head -n 5
NAME                      	RIG                              	VERSION      
act                       	github.com/bacongobbler/fish-food	0.2.24       
aks-engine                	github.com/bacongobbler/fish-food	0.66.0       
anycable-go               	github.com/bacongobbler/fish-food	1.1.2        
argocd                    	github.com/bacongobbler/fish-food	2.0.5
```

**Comment by bacongobbler** [comment]
Check and make sure you're using the latest version of gofish?

**Comment by bacongobbler** [comment]
It is possible that Gofish may not be purging all of its cached data on a `gofish remove`. Try purging any directories that are listed out with `gofish tank` and try again.

**Comment by shakefu** [comment]
> Check and make sure you're using the latest version of gofish?

Just installed following the install script instructions in the documentation a few hours ago.

![image](https://user-images.githubusercontent.com/1046227/133161776-e3ff7e0f-c692-4d46-b0c3-6eb67e65d47f.png)

Also I just noticed that `go` is listed twice in the output from search, but with the same repo:
![image](https://user-images.githubusercontent.com/1046227/133175607-8b6eb1cf-0da4-4d08-85e2-8943b12288a1.png)

I'll try purging.

**Comment by shakefu** [comment]
Just closing this cause I never got it working but also never went far into debugging why my setup was broken.
