### ISSUE TITLE
request: consider releasing binaries in github releases - goreleaser

### ISSUE THREAD

**Issue by stuart-warren** [fishworks/gofish#189]
Is there any desire to use [goreleaser](https://github.com/goreleaser/goreleaser) to build and upload releases to github rather than just/in addition to uploading to https://gofi.sh/releases/?

the main benefit is creating various other package formats (deb/rpm) etc and/or push to a package repo like [artifactory](https://jfrog.com/artifactory/) or [gemfury](https://gemfury.com/)

goreleaser itself should have support for maintaining a gofish "Rig" [soon](https://github.com/goreleaser/goreleaser/issues/2420) 🥳

**Comment by bacongobbler** [comment]
No, but thank you for asking.
