### ISSUE TITLE
darwin-arm64 build

### ISSUE THREAD

**Issue by arbourd** [fishworks/gofish#198]
Hi! 

Do you think we could get a manual rebuild of v0.14.0 or a minor v0.14.1 bump, so that the darwin-arm64 binary appears at:
https://gofi.sh/releases/gofish-v0.14.0-darwin-arm64.tar.gz

**Comment by bacongobbler** [comment]
I’m on vacation at the moment. When I return next week, I’ll cut a new release. Please feel free to ping me if I forget.

**Comment by arbourd** [comment]
Bumpity bump

**Comment by bacongobbler** [comment]
I haven’t forgotten! Just working through jet lag. Thanks for being patient.

**Comment by arbourd** [comment]
ya no real rush! thanks. i hope you enjoyed your trip 😁

**Comment by bacongobbler** [comment]
https://github.com/fishworks/gofish/releases/tag/v0.15.0
