### ISSUE TITLE
display error on `gofish install` to run `gofish link` when linking fails

### ISSUE THREAD

**Issue by bacongobbler** [fishworks/gofish#20]

**Comment by bacongobbler** [comment]
it's been a long while since you initially commented, @tomlazar. Just checking in to see if you made any progress here.

**Comment by tomlazar** [comment]
I can't say that I have, just took a look at the code. It would be pretty simple to do a `fmt.Errorf` or a `errors.Wrap` if either the `food.Unlink` or `food.Link` fails and just add in some text saying `Error while (Un)linking: %v, try running 'gofish (un)link;"

**Comment by bacongobbler** [comment]
okay. Feel free to contribute something.
