### ISSUE TITLE
Proposal: `gofish install food@version`

### ISSUE THREAD

**Issue by notlmn** [fishworks/gofish#65]
Scoop does this kind of installation automatically by creating a temporary manifest file (it also has [a way to check hash](https://github.com/lukesampson/scoop/blob/master/bucket/nodejs.json#L45) for a specific version, which is optional).

![image](https://user-images.githubusercontent.com/37769974/39087241-e0834b9c-45bb-11e8-9771-dca23e5e3a12.png)

--------------------

I think this should be the basis fo `gofish switch <food> <version>`, as there is no way to install an app say of version `0.0.2` if the user has installed `gofish` after that app is updated to `0.0.3`?

**Comment by bacongobbler** [comment]
After thinking about this proposal for the last few months, I'm marking this as out of scope for the design of GoFish. The Homebrew community has reconciled around [checking out a previous version of the repository](https://stackoverflow.com/questions/3987683/homebrew-install-specific-version-of-formula) to get an older version of a formula, which is much safer alternative.

To illustrate a few points on why we won't support this:

1. GoFish considers the package's integrity as a core value proposition of the project. Hashes will not come from outside of the package, as it can with Scoop. That breaks integrity; how can we be sure that the text file from an extenal URL has not been tampered?
2. older/newer versions of the package may have different release assets. GoFish needs to know about that.
