### ISSUE TITLE
Proposal: Named rigs

### ISSUE THREAD

**Issue by notlmn** [fishworks/gofish#66]
Named rigs are just like named remotes in git.

Each rig is identified by its name and not by its mini-url-thingy (github.com/fishworks/fishfood), this makes it easy to manage (add, remove, update, list) rigs and also makes it easy to work with #32.

## Proposed rig commands
```
gofish rig add <name> <url>
gofish rig rename <old> <new>
gofish rig remove <name>
gofish rig get <name>
gofish rig get <name> --path     <-- this itself can be #32
gofish rig set <name> <new-url>
```

**Comment by bacongobbler** [comment]
This sounds like a great idea. What do you think about switching the name and URL fields around on `gofish rig add` and making the name optional? That way, the existing behaviour of `gofish rig add https://...` works the same as it does now, implying the name based on the URL. This would allow the existing behaviour to stay as-is while giving us the flexibility to re-name rigs as the user chooses.

**Comment by notlmn** [comment]
I know you are aiming for backwards compatibility, but as the software is still in its beta stage, I hope a little API change would not cause a lot of problem.

I'm thinking of making it similar to `git remote add`, which every developer using git is used to.

**Comment by bacongobbler** [comment]
Actually it's not about backwards compatibility but about decreasing complexity for the user. I believe users should definitely have a way to re-name their rig names as they see fit, but in the default case, it should be informed based on the URL given. I strongly believe that the name a user names a rig does not have an affect on the core experience. We just need to provide a sane name out of the box that are a best-effort prevention in name collisions.

Take a typical custom rig example:

- I, as a user, want to install package X
- package X does not exist in core, but in a rig
- package X is a unique fish food with no name collisions with anything in core

In that case, if a user is to ask for `gofish install X`, one can expect that the only logical package that user wants to install is from the custom rig. In that situation (and I'd argue that is how most homebrew taps are used today), the name of the rig does not matter.

Does that make sense?

**Comment by bacongobbler** [comment]
Keep in mind that this is my assumption on the 80% use case, which is what I want to strive for. For the other 20%, custom rig names make sense.

**Comment by notlmn** [comment]
My take on named rigs is that the user should be able to know in which rig a package is available (or the package is installed from). And I suggested `gofish rig add <name> <url>` because users are already used to this format as git remotes.

----------

Homebrew uses [`user/repo` format](https://github.com/Homebrew/brew/blob/master/docs/Taps.md#the-command-brew-tap) as the name of a rig, and also as the url if no url is specified explicitly. The url is computed to be `https://github.com/user/repo`, or **user can specify a url explicitly**.

But gofish uses the full path of a repo as an identifer (using the hostname too), it is very unlikely that a user adds rigs like `github.com/x/y` and same `x/y` from gitlab. So an indentifier (rig name) like `user/repo` would be enough.

-------------

> We just need to provide a sane name out of the box that are a best-effort prevention in name collisions.

Restrict the rig name to be of `user/repo` format (like homebrew)?

-----------

> the name of the rig does not matter

But in case of a collision, the user should be able to `gofish install <rig-name>/package`.
