### ISSUE TITLE
Suggestion: Better logging of fish food

### ISSUE THREAD

**Issue by notlmn** [fishworks/gofish#67]
## Note

This issue builds upon #65 and #66. If any of them are not implemented, then this suggestion changes too!

-------------

## Problem

The current implementation of displaying information of fish food is limited to only its name, which is not helpful.

For example, `gofish search` displays available fish foods with tab as separator, other information like version, rig are left out.

```
$ gofish search
chartmuseum                     draft                   helm                    hugo                kubectl                     minikube                        acs-engine                      brig                    go                      gofish
```

-------

### Search fish
```
$ gofish search
'fishfood' rig:
    chartmuseum (0.0.0)
    draft (0.0.0)
    go (0.0.0)

'some-other' rig:
    chrome (0.0.0)
    chromium (0.0.0)
```

### List installed fish
```
$ gofish list
Installed fish:

  gofish 0.0.0 [rig-name] (upgradable)
  go 0.0.0 [rig-name]

```

```
$ gofish list go
Using go 0.0.3 from <rig-name>
Open source programming language to build simple/reliable/efficient software

Installed versions:
  0.0.4 [<rig-name>]
* 0.0.3 [<rig-name>]
  0.0.2 [<path-to-lua-file>]
  0.0.1 [<rig-name>]

Use 'gofish switch go <version>' to select a different version.

Newer version of this fish is available, run 'gofish upgrade go' to install the newer version.
```

### Fish info
```
$ gofish info <fish-name>
<fish-name>: <fish-version> [<fish-rig>]
<fish-description>
<fish-homepage>

Installed
	from: <fish-url>
	to: <fish-path-on-disk>
```

~Either `gofish list <app-name>` or `gofish info <app-name>` are to be used, and the other one needs to be dropped as this feels redundant.~ _**See updates below**_

### List rigs
```
$ gofish rig list
fishfood    https://github.com/fishworks/fishfood
<rig-name>  <rig-url>
```

---------------

**Updates:**
* list and info are treated separate
  * list shows all available installed versions
  * info shows currently selected version

**Comment by bacongobbler** [comment]
I like this. However, I would like to have a consistent UI across commands to parse out relevant information. In certain commands I've implemented a table-based approach to output such as `gofish rotten`. That makes it easy to parse out information using `grep`, `awk` and other CLI tools.

Would a table-based approach be good here, or is it important that the output is similar to tools like Homebrew and Scoop?

**Comment by notlmn** [comment]
The sample output was just examples, which can be improved as our discussion progresses.

-------------

> Would a table-based approach be good here

Yes in case of listing similar items in case of searching for food or listing installed food and rigs, bit not in case of food info because it is a single entity by itself.

------------

> or is it important that the output is similar to tools like Homebrew and Scoop?

Just taking some inspiration on what to show to the user

---------------

> I would like to have a consistent UI

Me too
