### ISSUE TITLE
Cannot install fish food from a custom rig

### ISSUE THREAD

**Issue by pinterb** [fishworks/gofish#75]
I was experimenting with my own food.  I was able to add this rig to my local fish tank.  However, when I attempt to install my own food, it appears fish only searches the default rig's path.

I assumed there was a way to either switch the rig "context" to a rig of my choice, OR that gofish install would search on install rigs.

I'm guessing it's user error.  So it would be helpful if you could clarify.

**Comment by bacongobbler** [comment]
Updated the title to reflect the issue.
