### ISSUE TITLE
GoFish install does not work on WSL

### ISSUE THREAD

**Issue by cnadolny** [fishworks/gofish#89]
Output after running install command:

curl -fsSL https://raw.githubusercontent.com/fishworks/gofish/master/scripts/install.sh | bash
Downloading https://gofi.sh/releases/gofish-v0.6.2-linux-amd64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 4078k  100 4078k    0     0  4599k      0 --:--:-- --:--:-- --:--:-- 4599k
Preparing to install into /usr/local/bin
cp: cannot stat '/tmp/gofish/linux-amd64/CLAUDIA-DEV/gofish': No such file or directory
!!!     Failed to install gofish
!!!     For support, go to https://github.com/fishworks/gofish.

It looks like the issue is that the $NAME variable is being appended between linux-amd64/gofish.

**Comment by bacongobbler** [comment]
Good catch. https://github.com/fishworks/gofish/blob/5d590cdfe038ff263c6b5ec938e07d3381dc2cfd/scripts/install.sh#L101 should probably be changed to use $PROJECT_NAME instead. Let me test that out and see what happens.

In the meantime, you should just be able to `mv /tmp/gofish/linux-amd64/gofish /usr/local/bin` and be up and running. :)
