### ISSUE TITLE
gofish init fails on fedora under AD user

### ISSUE THREAD

**Issue by cosminilie** [fishworks/gofish#93]
Hi,

My desktop is a Fedora  (Fedora 28 - 4.16.14-300.fc28.x86_64) machine configured with sssd to connect to an windows Active Directory domain in order to allow login with domain users. In this case my identity is  `username@example.net' and the group is 'domain users@example.net`.

When i run gofish init i get the following error:
```sh
○ → gofish init
The following new directories will be created:
/usr/local/Fish
/usr/local/Fish/Barrel
/usr/local/Fish/Rigs
/usr/local/bin
/home/username@example.net/.gofish
chown: invalid group: ‘username@example.net:username@example.net’
Error: exit status 1
```
For the chown command to work in my case you would need to run:

```sh
 chown username@example.net:"domain users@example.net" /home/username@example.net/.gofish
```

To fix this you would need to change this line: https://github.com/fishworks/gofish/blob/master/cmd/gofish/ensure_unix.go#L30 and get the group, which might be different than the user. You can use something like `id -gn $USER` to get the group name.

**Comment by bacongobbler** [comment]
thanks for the feedback! Please feel free to PR a fix for this. :)
